branch-defaults:
  docker:
    environment: monolithstarter-stage
  master:
    environment: monolithstarter-stage
environment-defaults:
  monolithstarter-stage:
    branch: null
    repository: null
global:
  application_name: monolithstarter
  default_ec2_keyname: aws-ssh-eb
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Docker running on 64bit Amazon Linux/2.12.10
  default_region: us-east-1
  workspace_type: Application
